apiVersion: v1
kind: Pod
metadata:
  name: debug-tpu-sglang-score
  namespace: eval-serving
  labels:
    app: debug-tpu-sglang-score
    ai.gke.io/inference-server: sglang-jax
  annotations:
    gke-gcsfuse/volumes: "true"
    gke-gcsfuse/cpu-limit: "0"
    gke-gcsfuse/memory-limit: "0"
    gke-gcsfuse/ephemeral-storage-limit: "0"
spec:
  serviceAccountName: eval-serving-sa
  nodeSelector:
    cloud.google.com/gke-tpu-topology: 1x1
    cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
  containers:
  - name: inference-server
    # Use a pre-existing image or the one we build. 
    # Since we plan to copy files/rebuild inside, let's use a base image or the existing vllm one if compatible, 
    # BUT better to use something that has python/jax installed if possible.
    # The user example used: europe-docker.pkg.dev/ashires-e7aaot/container/vllm-tpu:pr
    # Let's use the one from the user example for now as a base environment, 
    # assuming it has basic tools, or we might need to install things.
    # actually, if we want to run sglang-jax, we probably want an image with jax[tpu] pre-installed if possible.
    # Let's stick to the prompt's suggested image for now to ensure node compatibility.
    image: europe-docker.pkg.dev/ashires-e7aaot/container/vllm-tpu:pr
    imagePullPolicy: Always
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      requests:
        cpu: "24"
        memory: "100Gi"
        ephemeral-storage: "10Gi"
        google.com/tpu: "1"
      limits:
        cpu: "24"
        memory: "100Gi"
        ephemeral-storage: "10Gi"
        google.com/tpu: "1"
    volumeMounts:
    - name: gcs-fuse-csi-ephemeral
      mountPath: /data
    - name: dshm
      mountPath: /dev/shm
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: gke-gcsfuse-cache
    emptyDir:
      medium: Memory
  - name: dshm
    emptyDir:
      medium: Memory
  - name: tmp
    emptyDir:
      medium: Memory
  - name: gcs-fuse-csi-ephemeral
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: ashires-e7aaot-model-download-europe-west4
        mountOptions: "implicit-dirs,file-cache:enable-parallel-downloads:true,file-cache:parallel-downloads-per-file:100,file-cache:max-parallel-downloads:-1,file-cache:download-chunk-size-mb:10,file-cache:max-size-mb:-1" 
