apiVersion: batch/v1
kind: Job
metadata:
  generateName: sglang-benchmark-
  namespace: eval-serving
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/cpu-limit: "0"
        gke-gcsfuse/memory-limit: "0"
        gke-gcsfuse/ephemeral-storage-limit: "0"
    spec:
      serviceAccountName: eval-serving-sa
      nodeSelector:
        cloud.google.com/gke-tpu-topology: "1x1"
        cloud.google.com/gke-tpu-accelerator: "tpu-v6e-slice"
      restartPolicy: Never
      containers:
      - name: benchmark
        image: europe-docker.pkg.dev/ashires-e7aaot/container/vllm-tpu:pr
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "24"
            memory: "100Gi"
            ephemeral-storage: "10Gi"
            google.com/tpu: "1"
          limits:
            cpu: "24"
            memory: "100Gi"
            ephemeral-storage: "10Gi"
            google.com/tpu: "1"
        command:
        - "/bin/bash"
        - "-c"
        - |
          set -e
          echo "Starting benchmark job..."
          
          # Install git if needed
          apt-get update && apt-get install -y git
          
          # Clone sglang-jax
          # We need sglang-jax for the benchmark script and potentially to run the server
          # For now, we assume we are running 'all-in-one' (server + bench in same pod)
          # OR we are targeting a remote server. 
          # The user asked for "fresh manifests", implying a self-contained job is good.
          # The most reliable way for benchmarking is usually all-in-one to avoid network noise,
          # BUT sGLANG usually runs as a server.
          # Let's run the server in the background and then run the benchmark.
          
          echo "Cloning sglang-jax..."
          git clone https://github.com/alexshires/sglang-jax.git
          cd sglang-jax
          git checkout fix/score-api-missing-logprobs
          
          echo "Installing..."
          cd python
          pip install -e .[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
          cd ..
          
          # Start Server in background
          echo "Starting SGLang Zero-1 Server..."
          # Note: Adjust parameters as needed (e.g. model path)
          python3 -m sgl_jax.launch_server \
            --model deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B \
            --host 0.0.0.0 \
            --port 30000 \
            --tp-size 1 \
            --variable-partition-size 4 \
            &
            
          SERVER_PID=$!
          
          # Wait for server
          echo "Waiting for server to be ready..."
          timeout 600 bash -c 'while ! curl -s http://localhost:30000/health; do sleep 5; done'
          
          echo "Server ready. Running benchmark..."
          
          # Run Benchmark
          python3 python/sgl_jax/bench_score.py \
            --tokenizer deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B \
            --num-requests 1000 \
            --concurrency 32 \
            --query-len 128 \
            --num-items 4 \
            --item-len 32
            
          EXIT_CODE=$?
          
          # Cleanup
          kill $SERVER_PID
          
          exit $EXIT_CODE
        volumeMounts:
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: gke-gcsfuse-cache
        emptyDir:
          medium: Memory
      - name: dshm
        emptyDir:
          medium: Memory
      - name: tmp
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: ashires-e7aaot-model-download-europe-west4
            mountOptions: "implicit-dirs,file-cache:enable-parallel-downloads:true,file-cache:parallel-downloads-per-file:100,file-cache:max-parallel-downloads:-1,file-cache:download-chunk-size-mb:10,file-cache:max-size-mb:-1"
  backoffLimit: 0
